# Generated by Django 3.1.7 on 2021-09-28 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='user_id')),
                ('display_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='user_name')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
                ('deleted_flag', models.BooleanField(default=False, verbose_name='deleted_flag')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField(blank=True, null=True, verbose_name='reservation_date')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='update_at')),
                ('done_flag', models.BooleanField(default=False, verbose_name='done_flag')),
                ('content', models.TextField()),
                ('hospital_num', models.CharField(max_length=50, verbose_name='hospital_num')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='reserve_system.user')),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
    ]
