# Generated by Django 3.1.7 on 2021-10-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='content',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='hospital_num',
        ),
    ]
