# Generated by Django 3.1.7 on 2021-10-03 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_system', '0002_auto_20211003_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='reservation_date'),
        ),
    ]
